src/SimplCommerce.Web/ViewModels/Checkout/AddressFormViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace SimplCommerce.Web.ViewModels.Checkout
{
    public class AddressFormViewModel
    {
        [Required]
        public string ContactName { get; set; }

        [Required]
        public string Phone { get; set; }

        [Required]
        public string AddressLine1 { get; set; }

        public long StateOrProvinceId { get; set; }

        public long DistrictId { get; set; }

        public IList<SelectListItem> StateOrProvinces{ get; set; }

        public IList<SelectListItem> Districts { get; set; } 
    }
}

src/SimplCommerce.Web/ViewModels/Checkout/DeliveryInformationViewModel.cs
using System.Collections.Generic;

namespace SimplCommerce.Web.ViewModels.Checkout
{
    public class DeliveryInformationViewModel
    {
        public DeliveryInformationViewModel()
        {
            NewAddressForm = new AddressFormViewModel();
        }

        public IList<ShippingAddressViewModel> ExistingShippingAddresses { get; set; } =
            new List<ShippingAddressViewModel>();

        public long ShippingAddressId { get; set; }

        public AddressFormViewModel NewAddressForm { get; set; }
    }
}

src/SimplCommerce.Web/ViewModels/Checkout/ShippingAddressViewModel.cs
namespace SimplCommerce.Web.ViewModels.Checkout
{
    public class ShippingAddressViewModel
    {
        public long UserAddressId { get; set; }

        public string ContactName { get; set; }

        public string Phone { get; set; }

        public string AddressLine1 { get; set; }

        public string AddressLine2 { get; set; }

        public string DistrictName { get; set; }

        public string StateOrProvinceName { get; set; }

        public string CountryName { get; set; }
    }
}

src/SimplCommerce.Web/Components/OrderSummaryViewComponent.cs
using SimplCommerce.Orders.ApplicationServices;
using SimplCommerce.Web.ViewModels.Cart;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using SimplCommerce.Core.Domain.Models;

namespace SimplCommerce.Web.Components
{
    public class OrderSummaryViewComponent : ViewComponent
    {
        private readonly ICartService cartService;
        private readonly UserManager<User> userManager;

        public OrderSummaryViewComponent(ICartService cartService, UserManager<User> userManager)
        {
            this.cartService = cartService;
            this.userManager = userManager;
        }

        public IViewComponentResult Invoke()
        {
            var userId = long.Parse(userManager.GetUserId(HttpContext.User));

            var cartItems = cartService.GetCartItems(userId, null);
            var model = new CartViewModel
            {
                CartItems = cartItems.Select(x => new CartListItem
                {
                    Id = x.Id,
                    ProductName = x.Product.Name,
                    ProductPrice = x.ProductPrice,
                    Quantity = x.Quantity,
                    VariationOptions = CartListItem.GetVariationOption(x.ProductVariation)
                }).ToList()
            };

            return View(model);
        }
    }
}

src/SimplCommerce.Web/Controllers/CheckoutController.cs
using System.Linq;
using SimplCommerce.Core.Domain.Models;
using SimplCommerce.Infrastructure.Domain.IRepositories;
using SimplCommerce.Orders.ApplicationServices;
using SimplCommerce.Web.ViewModels.Checkout;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace SimplCommerce.Web.Controllers
{
    [Authorize]
    public class CheckoutController : BaseController
    {
        private IRepository<StateOrProvince> stateOrProvinceRepository;
        private IRepository<District> districtRepository;
        private IRepository<UserAddress> userAddressRepository;
        private IRepository<User> userRepository;
        private IOrderService orderService;

        public CheckoutController(
            UserManager<User> userManager,
            IRepository<StateOrProvince> stateOrProvinceRepository,
            IRepository<District> districtRepository,
            IRepository<UserAddress> userAddressRepository,
            IRepository<User> userRepository,
            IOrderService orderService) : base(userManager)
        {
            this.stateOrProvinceRepository = stateOrProvinceRepository;
            this.districtRepository = districtRepository;
            this.userAddressRepository = userAddressRepository;
            this.userRepository = userRepository;
            this.orderService = orderService;
        }

        public IActionResult Index()
        {
            return RedirectToAction("DeliveryInformation");
        }

        [HttpGet]
        public IActionResult DeliveryInformation()
        {
            var model = new DeliveryInformationViewModel();

            model.ExistingShippingAddresses = userAddressRepository
                .Query()
                .Where(x => x.AddressType == AddressType.Shipping && x.UserId == CurrentUserId)
                .Select(x => new ShippingAddressViewModel
                {
                    UserAddressId = x.Id,
                    ContactName = x.Address.ContactName,
                    Phone = x.Address.Phone,
                    AddressLine1 = x.Address.AddressLine1,
                    AddressLine2 = x.Address.AddressLine1,
                    DistrictName = x.Address.District.Name,
                    StateOrProvinceName = x.Address.StateOrProvince.Name,
                    CountryName = x.Address.Country.Name
                }).ToList();

            model.NewAddressForm.StateOrProvinces = stateOrProvinceRepository
                .Query()
                .OrderBy(x => x.Name)
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }).ToList();

            var selectedStateOrProvince = long.Parse(model.NewAddressForm.StateOrProvinces.First().Value);

            model.NewAddressForm.Districts = districtRepository
                .Query()
                .Where(x => x.StateOrProvinceId == selectedStateOrProvince)
                .OrderBy(x => x.Name)
                .Select(x => new SelectListItem
                 {
                     Text = x.Name,
                     Value = x.Id.ToString()
                 }).ToList();

            return View(model);
        }

        [HttpPost]
        public IActionResult DeliveryInformation(DeliveryInformationViewModel model)
        {
            if (!ModelState.IsValid && model.ShippingAddressId == 0)
            {
                return View(model);
            }

            var user = userRepository.Query().FirstOrDefault(x => x.Id == CurrentUserId);

            if (model.ShippingAddressId == 0)
            {
                var address = new Address
                {
                    AddressLine1 = model.NewAddressForm.AddressLine1,
                    ContactName = model.NewAddressForm.ContactName,
                    CountryId = 1,
                    StateOrProvinceId = model.NewAddressForm.StateOrProvinceId,
                    DistrictId = model.NewAddressForm.DistrictId,
                    Phone = model.NewAddressForm.Phone
                };

                var userAddress = new UserAddress
                {
                    Address = address,
                    AddressType = AddressType.Shipping,
                    UserId = CurrentUserId
                };

                userAddressRepository.Add(userAddress);
                user.CurrentShippingAddress = userAddress;
            }
            else
            {
                user.CurrentShippingAddress = userAddressRepository.Query().FirstOrDefault(x => x.Id == model.ShippingAddressId);
            }
            orderService.CreateOrder(user);
            userAddressRepository.SaveChange();

            return RedirectToAction("OrderConfirmation");
        }

        [HttpGet]
        public IActionResult OrderConfirmation()
        {
            return View();
        }
    }
}

src/SimplCommerce.Web/Views/Checkout/DeliveryInformation.cshtml
@model SimplCommerce.Web.ViewModels.Checkout.DeliveryInformationViewModel

@{
    ViewBag.Title = "Delivery Information";
}

<div class="row">
    <div class="col-md-7">
        <form asp-controller="Checkout" asp-action="DeliveryInformation" method="POST" id="checkout-delivery-address" class="form-horizontal">
            <h3>Shipping Address</h3>
            @foreach (var address in Model.ExistingShippingAddresses)
            {
                <div class="radio">
                    <label>
                        <input type="radio" name="shippingAddressId" value="@address.UserAddressId">
                        <strong>@address.ContactName </strong><br />
                        @address.AddressLine1 <br />
                        @address.DistrictName, @address.StateOrProvinceName <br />
                        Phone: @address.Phone
                    </label>
                </div>
            }
            <div class="radio">
                <label>
                    <input type="radio" name="shippingAddressId" value="0" />
                    Add another address
                </label>
            </div>
            <div class="create-shipping-address collapse">
                <div class="form-group">
                    <label class="col-sm-4 control-label">Contact Name</label>
                    <div class="col-sm-8">
                        <input asp-for="NewAddressForm.ContactName" type="text" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-4 control-label">Address</label>
                    <div class="col-sm-8">
                        <input asp-for="NewAddressForm.AddressLine1" type="text" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-4 control-label">State or Province</label>
                    <div class="col-sm-8">
                        <select asp-for="NewAddressForm.StateOrProvinceId" asp-items="Model.NewAddressForm.StateOrProvinces" class="form-control"></select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-4 control-label">District</label>
                    <div class="col-sm-8">
                        <select asp-for="NewAddressForm.DistrictId" asp-items="Model.NewAddressForm.Districts" class="form-control"></select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-4 control-label">Phone</label>
                    <div class="col-sm-8">
                        <input asp-for="NewAddressForm.Phone" type="text" class="form-control">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12 text-right">
                    <button type="submit" class="btn btn-primary">ORDER</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-5">
        @await Component.InvokeAsync("OrderSummary")
    </div>
</div>

@section scripts {
@{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script src="~/js/checkout/shipping.js"></script>
}